#! /usr/bin/python

import socket
import sys
import os
import json

PORT = 50007              # The same port as used by the server
error = "Error: goudabot not running on port " + str(PORT)


def send(command):
    HOST = 'localhost'    # The remote host
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.connect((HOST, PORT))
        s.sendall(command)
        data = s.recv(1024)
        s.close()
        print repr(data)
    except:
        print error

if __name__ == '__main__':
    sys.argv.append(os.getcwd())
    command = json.dumps(sys.argv[1:])
    send(command)
